services:
  - type: web
    name: suv-landing
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt && python manage.py migrate
    startCommand: gunicorn suv_landing.wsgi:application
    envVars:
      - key: DJANGO_SECRET_KEY
        generateValue: true
